/**
 * MenuSection tests
 */

import React from 'react';
import { describe, beforeEach, it } from 'mocha';
import { expect } from 'chai';

import { mount } from '../../../tests/helpers';

import MenuSection from '../MenuSection';
import MenuSectionInteractor from './interactor';

describe('MenuSection', () => {
  const menuSection = new MenuSectionInteractor();
  const label = 'My label';
  const labelTag = 'h2';
  const id = 'my-id';
  const content = <div>Some content</div>;
  const className = 'some-class-name';

  beforeEach(async () => {
    await mount(
      <MenuSection id={id} label={label} className={className} labelTag={labelTag}>
        {content}
      </MenuSection>
    );
  });

  it('Should apply an ID to the root element if provided', () => {
    expect(menuSection.id).to.equal(id);
  });

  it('Should render a label if a node/string is passed to the label-prop', () => {
    expect(menuSection.hasLabel).to.be.true;
  });

  it('Should render content when passing anything as children', () => {
    expect(menuSection.hasContent).to.be.true;
  });

  it('Should apply any custom class passed to the className-prop', () => {
    expect(menuSection.className).to.include(className);
  });

  it(`Should render a label (<Headline>) with a labelTag of ${labelTag}`, () => {
    expect(menuSection.labelTag).to.equal(labelTag);
  });

  describe('If no ID is provided', () => {
    beforeEach(async () => {
      await mount(
        <MenuSection />
      );
    });

    it('Should apply an autogenerated ID to the root element', () => {
      expect(menuSection.id).to.be.a('string');
    });
  });
});
