import React from 'react';
import Scrollable from '../Scrollable';

export default () => (
  <div style={{ width: '600px', height: '400px', border: '1px solid #ccc', margin: '15px' }}>
    <Scrollable>
      <div style={{ padding: '10px' }}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultrices tincidunt est, eu scelerisque diam dictum sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras non nulla a sapien facilisis laoreet. Suspendisse enim enim, semper sed nulla vitae, sodales ultricies justo. Mauris et urna turpis. Sed faucibus ipsum vitae tellus efficitur, id tempus nunc feugiat. Nam turpis magna, tincidunt id odio mollis, eleifend mollis lorem. Aenean orci turpis, cursus sit amet gravida nec, accumsan ut metus. Suspendisse a commodo tortor. Vestibulum vel dapibus lacus. Suspendisse eleifend est ac purus facilisis, in feugiat nibh suscipit. Suspendisse nibh est, iaculis ut venenatis id, tincidunt ut mauris. Nulla id augue rutrum nibh finibus sollicitudin a sit amet tellus. Pellentesque pellentesque dictum libero et suscipit. Sed dictum sagittis mauris id faucibus. Donec sed quam egestas, ullamcorper massa vitae, venenatis sem.
        <br /><br />
        Donec est lorem, fringilla sit amet lobortis ut, maximus et mauris. Duis bibendum tellus eu nisi semper pharetra. Curabitur tristique nisi dictum dignissim maximus. Suspendisse potenti. Nam dapibus, ipsum non posuere congue, ipsum justo dignissim ex, laoreet faucibus nulla nibh quis magna. Ut nec libero ultricies, elementum mi quis, ornare lacus. Nullam gravida blandit lacus, ut volutpat magna commodo sed. Integer at rhoncus purus. Phasellus dui purus, laoreet vitae dui nec, pretium dictum eros. Maecenas et odio aliquam, vulputate erat eu, sagittis ante. Donec congue, mauris at molestie eleifend, libero leo ultricies purus, at egestas urna ex id ligula.
        <br /><br />
        Vivamus nulla nisi, laoreet eu lectus in, consequat tincidunt sapien. Suspendisse potenti. Praesent id lacus ullamcorper, hendrerit nisi in, pharetra dui. Ut tincidunt erat eget ipsum aliquet ornare. Fusce congue volutpat erat id consectetur. Nullam convallis rutrum fringilla. Ut condimentum neque vulputate dapibus accumsan.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultrices tincidunt est, eu scelerisque diam dictum sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras non nulla a sapien facilisis laoreet. Suspendisse enim enim, semper sed nulla vitae, sodales ultricies justo. Mauris et urna turpis. Sed faucibus ipsum vitae tellus efficitur, id tempus nunc feugiat. Nam turpis magna, tincidunt id odio mollis, eleifend mollis lorem. Aenean orci turpis, cursus sit amet gravida nec, accumsan ut metus. Suspendisse a commodo tortor. Vestibulum vel dapibus lacus. Suspendisse eleifend est ac purus facilisis, in feugiat nibh suscipit. Suspendisse nibh est, iaculis ut venenatis id, tincidunt ut mauris. Nulla id augue rutrum nibh finibus sollicitudin a sit amet tellus. Pellentesque pellentesque dictum libero et suscipit. Sed dictum sagittis mauris id faucibus. Donec sed quam egestas, ullamcorper massa vitae, venenatis sem.
        <br /><br />
        Donec est lorem, fringilla sit amet lobortis ut, maximus et mauris. Duis bibendum tellus eu nisi semper pharetra. Curabitur tristique nisi dictum dignissim maximus. Suspendisse potenti. Nam dapibus, ipsum non posuere congue, ipsum justo dignissim ex, laoreet faucibus nulla nibh quis magna. Ut nec libero ultricies, elementum mi quis, ornare lacus. Nullam gravida blandit lacus, ut volutpat magna commodo sed. Integer at rhoncus purus. Phasellus dui purus, laoreet vitae dui nec, pretium dictum eros. Maecenas et odio aliquam, vulputate erat eu, sagittis ante. Donec congue, mauris at molestie eleifend, libero leo ultricies purus, at egestas urna ex id ligula.
        <br /><br />
        Vivamus nulla nisi, laoreet eu lectus in, consequat tincidunt sapien. Suspendisse potenti. Praesent id lacus ullamcorper, hendrerit nisi in, pharetra dui. Ut tincidunt erat eget ipsum aliquet ornare. Fusce congue volutpat erat id consectetur. Nullam convallis rutrum fringilla. Ut condimentum neque vulputate dapibus accumsan.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultrices tincidunt est, eu scelerisque diam dictum sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras non nulla a sapien facilisis laoreet. Suspendisse enim enim, semper sed nulla vitae, sodales ultricies justo. Mauris et urna turpis. Sed faucibus ipsum vitae tellus efficitur, id tempus nunc feugiat. Nam turpis magna, tincidunt id odio mollis, eleifend mollis lorem. Aenean orci turpis, cursus sit amet gravida nec, accumsan ut metus. Suspendisse a commodo tortor. Vestibulum vel dapibus lacus. Suspendisse eleifend est ac purus facilisis, in feugiat nibh suscipit. Suspendisse nibh est, iaculis ut venenatis id, tincidunt ut mauris. Nulla id augue rutrum nibh finibus sollicitudin a sit amet tellus. Pellentesque pellentesque dictum libero et suscipit. Sed dictum sagittis mauris id faucibus. Donec sed quam egestas, ullamcorper massa vitae, venenatis sem.
        <br /><br />
        Donec est lorem, fringilla sit amet lobortis ut, maximus et mauris. Duis bibendum tellus eu nisi semper pharetra. Curabitur tristique nisi dictum dignissim maximus. Suspendisse potenti. Nam dapibus, ipsum non posuere congue, ipsum justo dignissim ex, laoreet faucibus nulla nibh quis magna. Ut nec libero ultricies, elementum mi quis, ornare lacus. Nullam gravida blandit lacus, ut volutpat magna commodo sed. Integer at rhoncus purus. Phasellus dui purus, laoreet vitae dui nec, pretium dictum eros. Maecenas et odio aliquam, vulputate erat eu, sagittis ante. Donec congue, mauris at molestie eleifend, libero leo ultricies purus, at egestas urna ex id ligula.
        <br /><br />
        Vivamus nulla nisi, laoreet eu lectus in, consequat tincidunt sapien. Suspendisse potenti. Praesent id lacus ullamcorper, hendrerit nisi in, pharetra dui. Ut tincidunt erat eget ipsum aliquet ornare. Fusce congue volutpat erat id consectetur. Nullam convallis rutrum fringilla. Ut condimentum neque vulputate dapibus accumsan.
        <div style={{ width: '800px', height: '100px', background: 'yellow' }}>
          Very wide element
        </div>
      </div>
    </Scrollable>
  </div>
);
