# This is a basic workflow to build and publish stripes-components storybook

name: Build and Publish Storybook

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build-storybook:
    env:
      FOLIO_NPM_REGISTRY: 'https://repository.folio.org/repository/npm-folioci/'
      NODEJS_VERSION: '16'

    runs-on: ubuntu-latest

    steps:

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          check-latest: true
          always-auth: true

      - name: Set yarn config
        run: yarn config set @folio:registry $FOLIO_NPM_REGISTRY

      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Sync storybook branch
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     from_branch: master
      #     target_branch: storybook
      #     github_token: ${{ github.token }}

      - name: checkout storybook branch
        uses: actions/checkout@v3
        with:
          ref: storybook,
          fetch-depth: 0,

      - name: Run yarn install
        run: yarn install --ignore-scripts

      - name: Sync and Build storybook
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge master
          npm run storybook-build

      - name: Publish storybook
        run: |
          git add .
          git commit -am "update storybook"
          git push origin storybook
