# This is a basic workflow to help you get started with Actions

name: Build and Publish Storybook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-storybook"
  build-storybook:
    env:
      FOLIO_NPM_REGISTRY: 'https://repository.folio.org/repository/npm-folioci/'
      NODEJS_VERSION: '16'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ env.NODEJS_VERSION }}
                check-latest: true
                always-auth: true

      - name: Set yarn config
        run: yarn config set @folio:registry $FOLIO_NPM_REGISTRY

      - name: Run yarn install
        run: yarn install --ignore-scripts

      - name: Build and push storybook
        run: |
          echo git checkout storybook
          echo git merge master
          echo npm run storybook-build
          echo git add .
          echo git commit -am "update storybook"
          echo git push origin storybook
